name: drupal-canary-project
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: 2ed281d4-9dec-4cc3-ac63-691c3ba002c2
  ah_site_group: pipelinesvalidation2
  php: '8.1'
proxy:
  appserver:
    - drupal-canary-project.lndo.site
    - foo.drupal-canary-project.lndo.site
    - bar.drupal-canary-project.lndo.site
services:
  foo:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  bar:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
