version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.3

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
    SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"
        - validate:
            type: script
            script:
              - composer drupal:validate
        - setup-app:
            type: script
            script:
              - composer drupal:install
        - test:
            type: script
            script:
              - ./vendor/bin/drush runserver 8080 &
              - ./vendor/bin/phpunit -c docroot/core docroot/core --group=ban || true
        - build-artifact:
            type: script
            script:
              - mkdir /tmp/acli-push-artifact
              - acli push:artifact --no-push --no-clone --no-commit
              - shopt -s dotglob && rm -rf ./* && mv /tmp/acli-push-artifact/* ./
