version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.1

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - echo "first commit"
