version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.1

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"
        - validate:
            type: script
            script:
              - composer drupal:validate
        - setup-app:
            type: script
            script:
              - composer drupal:install
        - build-artifact:
            type: script
            script:
              - mkdir /tmp/acli-push-artifact
              - ./acli push:artifact --dry-run --no-clone --no-commit
              - mv .git /tmp/acli-push-artifact/
              - shopt -s dotglob && rm -rf ./* && mv /tmp/acli-push-artifact/* ./
